# Generated by Django 4.1.4 on 2022-12-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_rename_hosteldetails_hosteldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteldetail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='joiningdate',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='native',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='user',
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='firstname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='lastname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
