# Generated by Django 4.1.4 on 2023-01-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldetail',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
