# Generated by Django 4.1.4 on 2023-01-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_department_remove_hosteldetail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldetail',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
