# Generated by Django 4.1.4 on 2023-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_hosteldetail_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='Field',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='Semester',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='Timming',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
