# Generated by Django 4.1.4 on 2023-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Phone',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='password',
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
