# Generated by Django 4.1.5 on 2023-01-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_rename_phone_contactus_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldetail',
            name='mobile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
