# Generated by Django 4.1.5 on 2023-01-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_hosteldetail_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteldetail',
            name='mobile',
        ),
    ]
