# Generated by Django 4.1.5 on 2023-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_hosteldetail_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=100)),
                ('Semester', models.CharField(max_length=100)),
                ('Timming', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='Field',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='hosteldetail',
            name='Timming',
        ),
    ]
