# Generated by Django 4.1.5 on 2023-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_rename_department_studentdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdepartment',
            name='studentcode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
