# Generated by Django 4.1.5 on 2023-02-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_studentdepartment_studentcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(max_length=100)),
                ('Breakfast', models.CharField(max_length=100)),
                ('Launch', models.CharField(max_length=100)),
                ('Evening', models.CharField(max_length=100)),
                ('Dinner', models.CharField(max_length=100)),
                ('AtNight', models.CharField(max_length=100)),
            ],
        ),
    ]
