# Generated by Django 4.1.4 on 2023-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='sturoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOMNO', models.CharField(max_length=100)),
                ('BEDNO', models.CharField(max_length=100)),
                ('MEMBERS', models.CharField(max_length=100)),
                ('TABLE', models.CharField(max_length=100)),
                ('CHAIR', models.CharField(max_length=100)),
                ('CUPBOARD', models.CharField(max_length=100)),
            ],
        ),
    ]
