# Generated by Django 4.1.4 on 2023-02-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0023_sturoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sturoom',
            name='STUNAME',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
