# Generated by Django 4.1.4 on 2023-02-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0024_sturoom_stuname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sturoom',
        ),
    ]
