# Generated by Django 4.1.4 on 2023-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0027_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUNAME', models.CharField(max_length=100)),
                ('DAYS', models.CharField(max_length=100)),
                ('DATE', models.DateField(max_length=100)),
                ('PRESENT', models.CharField(max_length=100)),
                ('ABSENT', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='W',
        ),
    ]
