# Generated by Django 4.1.4 on 2023-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0028_stuattendance_delete_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuentery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUNAME', models.CharField(max_length=100)),
                ('DAYS', models.CharField(max_length=100)),
                ('DATE', models.DateField(max_length=100)),
                ('GOINGTIME', models.TimeField(max_length=100)),
                ('COMINGTIME', models.TimeField(max_length=100)),
            ],
        ),
    ]
