# Generated by Django 4.1.4 on 2023-02-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0030_alter_stuattendance_absent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sturoom',
        ),
    ]
